language: minimal

sudo: false

matrix:
  fast_finish: true
  include:
    - name: "python-3.7"
      env: PY=3.7
    - name: "tarball"
      env: PY=3.7

before_install:
  # Install miniconda and create TEST env.
  - |
    wget https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
    bash miniconda.sh -b -p $HOME/miniconda
    export PATH="$HOME/miniconda/bin:$PATH"
    conda config --set always_yes yes --set changeps1 no --set show_channel_urls true
    conda update --quiet conda
    conda config --add channels conda-forge --force
    conda config --set channel_priority strict
    conda config --set safety_checks disabled
    conda create --name TEST python=$PY --file requirements.txt --file requirements_dev.txt --file requirements_docs.txt --file requirements_plus.txt
    source activate TEST
    pip install bs4
    conda info --all

install:
  - pip install -e . --no-deps --force-reinstall

script:
  - if [[ $TRAVIS_JOB_NAME == python-* ]]; then
      python -c "from pysal.lib.examples import fetch_all; fetch_all()"; 
      travis_wait 45 nosetests --verbose --with-coverage --cover-package=pysal;
    fi

  - if [[ $TRAVIS_JOB_NAME == 'tarball' ]]; then
      pip wheel . -w dist --no-deps ;
      twine check dist/* ;
    fi

notifications:
    email:
        recipients:
            - sjsrey@gmail.com
            - levi.john.wolf@gmail.com
        on_success: change 
        on_failure: always

after_success:
  - coveralls
