language: python

sudo: false

matrix:
  include:
    - env: ENV_FILE="ci/travis/36-latest-conda-forge.yaml"
    - env: ENV_FILE="ci/travis/37-latest-conda-forge.yaml"
    - env: ENV_FILE="ci/travis/38-latest-conda-forge.yaml"

install:
  # Install conda
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - conda config --set always_yes yes --set changeps1 no
  - conda update conda
  - conda info


  # Install dependencies
  - conda env create --file="${ENV_FILE}"
  - source activate test
  - pip install -e .
  - conda list
  - python -c "import pysal; print(pysal.__version__);"

script:
  - py.test pysal --cov pysal -v --cov-report term-missing


notifications:
    email:
        recipients:
            - sjsrey@gmail.com
            - levi.john.wolf@gmail.com
        on_success: change 
        on_failure: always

after_success:
  - coveralls
