 name: Unit Tests
 on:
   push:
     branches:
     - '*'
   pull_request:
     branches:
     - '*'
   schedule:
     - cron: '59 23 * * *'

 jobs:
   unittests:
     name: CI (${{ matrix.os }}-${{ matrix.environment-file }})
     runs-on: ${{ matrix.os }}
     continue-on-error: ${{ matrix.experimental }}
     timeout-minutes: 90
     strategy:
       matrix:
         os: ['ubuntu-latest', 'macos-latest', 'windows-latest']
         environment-file: [ci/37.yml, ci/38.yml]
         experimental: [false]
     defaults:
       run:
         shell: bash -l {0}
     steps:
       - uses: actions/checkout@v4
       - uses: conda-incubator/setup-miniconda@v2
         with:
           environment-file: ${{ matrix.environment-file }}
           miniforge-version: latest
           miniforge-variant: Mambaforge
           use-mamba: true
           activate-environment: test
       - run: conda info --all
       - run: conda list
       - run: conda config --show-sources
       - run: conda config --show
       - run: pip install -e . --no-deps --force-reinstall
       - name: Pytest
         run: pytest -v pysal #--cov=pysal --cov-report=xml
       #- name: codecov (${{ matrix.os }}, ${{ matrix.environment-file }})
       #  uses: codecov/codecov-action@v1
       #  with:
       #    token: ${{ secrets.CODECOV_TOKEN }}
       #    file: ./coverage.xml
       #    name: pysal-codecov
